# Generated by Django 2.0 on 2019-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(db_column='C_id', max_length=20, primary_key=True, serialize=False, verbose_name='课程号')),
                ('c_name', models.CharField(blank=True, db_column='C_name', max_length=255, null=True, verbose_name='课程名')),
                ('t_id', models.CharField(blank=True, db_column='T_id', max_length=255, null=True, verbose_name='老师ID')),
                ('week', models.CharField(blank=True, db_column='Week', max_length=255, null=True, verbose_name='课程安排')),
            ],
            options={
                'verbose_name_plural': '课程',
                'db_table': 'course',
                'managed': False,
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='CRecord',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.CharField(blank=True, db_column='C_id', max_length=20, null=True, verbose_name='课程号')),
                ('c_name', models.CharField(blank=True, db_column='C_name', max_length=255, null=True, verbose_name='课程名')),
                ('notcome', models.CharField(blank=True, max_length=255, null=True, verbose_name='未到情况')),
                ('date', models.CharField(blank=True, db_column='Date', max_length=255, null=True, verbose_name='日期')),
                ('totalnum', models.IntegerField(blank=True, null=True, verbose_name='总人数')),
                ('realnum', models.IntegerField(blank=True, null=True, verbose_name='实到人数')),
            ],
            options={
                'verbose_name_plural': '考勤记录',
                'db_table': 'c_record',
                'managed': False,
                'verbose_name': '考勤记录',
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(db_column='S_id', max_length=20, verbose_name='学号')),
                ('c_name', models.CharField(db_column='C_name', max_length=20, null=True, verbose_name='课程名')),
            ],
            options={
                'verbose_name_plural': '学生选课情况',
                'db_table': 'learn',
                'managed': False,
                'verbose_name': '学生选课情况',
            },
        ),
        migrations.CreateModel(
            name='SRecord',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(db_column='S_id', max_length=20, verbose_name='学号')),
                ('c_id', models.CharField(db_column='C_id', max_length=20, verbose_name='课程号')),
                ('c_name', models.CharField(db_column='C_name', max_length=20, verbose_name='课程名')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='缺勤次数')),
            ],
            options={
                'verbose_name_plural': '学生考勤记录',
                'db_table': 's_record',
                'managed': False,
                'verbose_name': '学生考勤记录',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.CharField(db_column='S_id', max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('s_name', models.CharField(blank=True, db_column='S_name', max_length=20, null=True, verbose_name='姓名')),
                ('s_password', models.CharField(blank=True, db_column='S_password', max_length=20, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '学生',
                'db_table': 'student',
                'managed': False,
                'verbose_name': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.CharField(db_column='T_id', max_length=20, primary_key=True, serialize=False, verbose_name='教师编号')),
                ('t_name', models.CharField(blank=True, db_column='T_name', max_length=20, null=True, verbose_name='姓名')),
                ('t_password', models.CharField(blank=True, db_column='T_password', max_length=20, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '老师',
                'db_table': 'teacher',
                'managed': False,
                'verbose_name': '老师',
            },
        ),
    ]
